### PR TITLE
Added Support for all Package Metrics, Fixes #3

### LINKED ISSUE #3: List supported platforms in badge
This endpoint provides the platform list: https://pub.dev/api/packages/pana/metrics?pretty

image

Create a badge such as:

image

### PR DESCRIPTION
**Pull request by aldrinmathew**
Added Support for rendering all Package Metrics available in pub.dev API
This fixes Issue #3

### CODE REVIEW

**Comment by aldrinmathew** [comment]
@bruno-garcia

The tests are failing, especially those on the custom server, let me know how that can be fixed.

**Comment by bruno-garcia** [comment]
Thanks for the PR @AldrinMathew this is a great addition!

Sorry for the delay in reviewing it. I hope to get time on it soon.

I'm not sure yet why the tests fail. I'll pull your branch and debug them when I have a chance.

**Comment by aldrinmathew** [comment]
@bruno-garcia

No issues. Take your time. I will keep the PR open. Thanks for the response.

**Review by bruno-garcia — APPROVED** [review]
Thanks you for your contribution!
I'll get it merged and take a lot at the tests. I'm also thinking we could refactor this to support having only some of the values which is what happens in practice, at least on the `score` API.

**Comment by aldrinmathew** [comment]
@bruno-garcia 
Thanks for the quick turnaround and review. If there is anything I can do to help regarding this, let me know.

**Pull request merged**
