### PR TITLE
Add support for publisher badge

### PR DESCRIPTION
**Pull request by mit-mit**

### CODE REVIEW

**Comment by mit-mit** [comment]
@jonasfj does this look resonable?

**Comment by jonasfj** [comment]
Looks fine to me :D

**Comment by mit-mit** [comment]
CI issues should be resolved by https://github.com/bruno-garcia/badges.bar/pull/25

**Comment by mit-mit** [comment]
cc @bruno-garcia

**Review by bruno-garcia — APPROVED** [review]
LGTM! Thanks for this. I've added you as contributors to the repo.
I can update the service once we have changes merged in

**Comment by bruno-garcia** [comment]
Turns out CI broken (instead of pulling the fix into this branch I gambled and merged 😅 ). 

I can try to take a look at this in a few days

```
00:02 +2 -5: test/all_test.dart: getMetrics requests include User-Agent header [E]                                                                                                                     
  Can't parse metadata body because it's empty.
  package:badges_bar/src/pub_client.dart 55:7   PubClient._parseMetrics
  package:badges_bar/src/pub_client.dart 23:59  PubClient.getMetrics
  ===== asynchronous gap ===========================
  dart:async                                    _completeOnAsyncError
  package:badges_bar/src/pub_client.dart        PubClient._parseMetrics
  package:badges_bar/src/pub_client.dart 23:59  PubClient.getMetrics
  ===== asynchronous gap ===========================
  dart:async                                    _asyncThenWrapperHelper
  test/all_test.dart [70](https://github.com/bruno-garcia/badges.bar/runs/5572549429?check_suite_focus=true#step:5:70):43                      main.<fn>.<fn>
  test/all_test.dart 61:48                      main.<fn>.<fn>
  
  This test failed after it had already completed. Make sure to use [expectAsync]
  or the [completes] matcher when testing async code.
  package:badges_bar/src/pub_client.dart 55:7   PubClient._parseMetrics
  package:badges_bar/src/pub_client.dart 23:59  PubClient.getMetrics
  ===== asynchronous gap ===========================
  dart:async                                    _completeOnAsyncError
  package:badges_bar/src/pub_client.dart        PubClient._parseMetrics
  package:badges_bar/src/pub_client.dart 23:59  PubClient.getMetrics
  ===== asynchronous gap ===========================
  dart:async                                    _asyncThenWrapperHelper
  test/all_test.dart 70:43                      main.<fn>.<fn>
  test/all_test.dart 61:48                      main.<fn>.<fn>
```

**Pull request merged**
